
- name: Alice Johnson
  role: Leader
  image: /assets/img/prof_pic.jpg
  url: https://example.com/alice

- name: Bob Smith
  role: Leader
  image: /assets/img/profile/bob.jpg
  url: https://example.com/bob

- name: Carol Lee
  role: Member
  image: /assets/img/prof_pic.jpg
  url: https://example.com/carol

- name: David Kim
  role: Member
  image: /assets/img/profile/david.jpg
  url: https://example.com/david

- name: Eva Brown
  role: Member
  image: /assets/img/profile/eva.jpg
  url: https://example.com/eva

- name: Arnadi Murtiyoso
  role: Chair
  image: /assets/img/profile/arnadi.jpg
  url: https://murtiad.github.io/
